{
 "title": "Docker",
 "description": "A simple overview of the most important Docker host and container metrics. (cAdvisor/Prometheus)",
 "tags": [ "docker" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "containergroup",
    "label": "Container Group",
    "query": "label_values(container_label_container_group)"
   },
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(container_last_seen, node)"
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "2m,3m,5m,7m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage per Container (Stacked)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=~\".+\",node=~\"$node\",container_label_container_group=~\"$containergroup\"}[$interval])) by (name) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Usage per Container (Stacked)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_rss{name=~\".+\",node=~\"$node\",container_label_container_group=~\"$containergroup\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Cached Memory per Container (Stacked)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_cache{name=~\".+\",node=~\"$node\",container_label_container_group=~\"$containergroup\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Received Network Traffic per Container",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{name=~\".+\",node=~\"$node\",container_label_container_group=~\"$containergroup\"}[$interval])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Sent Network Traffic per Container",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{name=~\".+\",node=~\"$node\",container_label_container_group=~\"$containergroup\"}[$interval])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Running Containers (by Container Group)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "count(rate(container_last_seen{name=~\".+\",node=~\"$node\",container_label_container_group=\"monitoring\"}[$interval]))",
     "legendFormat": "Monitoring"
    },
    {
     "expr": "count(rate(container_last_seen{name=~\".+\",node=~\"$node\",container_label_container_group=\"backup\"}[$interval]))",
     "legendFormat": "Backup"
    },
    {
     "expr": "count(rate(container_last_seen{name=~\".+\",node=~\"$node\",container_label_container_group=\"other\"}[$interval]))",
     "legendFormat": "Other"
    },
    {
     "expr": "count(rate(container_last_seen{name=~\".+\",node=~\"$node\",container_label_container_group=\"lbs\"}[$interval]))",
     "legendFormat": "Load balancers"
    },
    {
     "expr": "count(rate(container_last_seen{name=~\".+\",node=~\"$node\",container_label_container_group=\"webhooks\"}[$interval]))",
     "legendFormat": "Webhooks"
    },
    {
     "expr": "count(rate(container_last_seen{name=~\".+\",node=~\"$node\",container_label_container_group=\"puppet\"}[$interval]))",
     "legendFormat": "Puppet"
    },
    {
     "expr": "count(rate(container_last_seen{name=~\".+\",node=~\"$node\",container_label_container_group=\"logs\"}[$interval]))",
     "legendFormat": "Logs"
    }
   ]
  }
 ]
}